inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'tmp/*'
    - Guardfile
    - Gemfile
    - 'node_modules/**/*'

Documentation:
  Enabled: false
